// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD2U081vVJbrn6I03JBDld_et2vxTBg1o',
    appId: '1:157074068847:web:444947db60eda778cd049a',
    messagingSenderId: '157074068847',
    projectId: 'moharrek-ac3cd',
    authDomain: 'moharrek-ac3cd.firebaseapp.com',
    storageBucket: 'moharrek-ac3cd.appspot.com',
    measurementId: 'G-XY7B30MX4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTP49ZlGBgOoupL60oVq9PwmoRY_ARKLE',
    appId: '1:942565308086:android:91343b1f283c4a0008d817',
    messagingSenderId: '942565308086',
    projectId: 'authcleanarch',
    storageBucket: 'authcleanarch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_xAu1AMspX2h9PoYGXCcaN-NN3Rvg5Q',
    appId: '1:157074068847:ios:acb676d32db3c6c0cd049a',
    messagingSenderId: '157074068847',
    projectId: 'moharrek-ac3cd',
    storageBucket: 'moharrek-ac3cd.appspot.com',
    iosBundleId: 'com.example.moharrek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm_xAu1AMspX2h9PoYGXCcaN-NN3Rvg5Q',
    appId: '1:157074068847:ios:acb676d32db3c6c0cd049a',
    messagingSenderId: '157074068847',
    projectId: 'moharrek-ac3cd',
    storageBucket: 'moharrek-ac3cd.appspot.com',
    iosBundleId: 'com.example.moharrek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD2U081vVJbrn6I03JBDld_et2vxTBg1o',
    appId: '1:157074068847:web:33e88878e60b1c77cd049a',
    messagingSenderId: '157074068847',
    projectId: 'moharrek-ac3cd',
    authDomain: 'moharrek-ac3cd.firebaseapp.com',
    storageBucket: 'moharrek-ac3cd.appspot.com',
    measurementId: 'G-53FR7WBP9N',
  );

}